[package]
name = "raytracer"
version = "0.1.0"
authors = ["Bart Massey <bart@cs.pdx.edu>"]
publish = false
description = "Raytracer in Rust."
repository = ""
readme = "README.md"
license = "MIT"

[lib]
name = "rt"
path = "lib/mod.rs"

[dependencies]
lazy_static = "0.2"
