[package]
name = "rt"
version = "0.1.0"
authors = ["Bart Massey <bart@cs.pdx.edu>"]
publish = false
description = "Raytracer in Rust."
repository = "http://github.com/BartMassey/phoenix-raytracer"
readme = "README.md"
license-file = "COPYING"
edition = "2021"
