[package]
name = "rt"
version = "0.1.0"
authors = ["Bart Massey <bart@cs.pdx.edu>"]
publish = false
description = "Raytracer in Rust."
repository = ""
readme = "README.md"
license = "MIT"
edition = "2021"
